feat: rate limit
MurmurationsNetwork/MurmurationsServices pull request #123
Opened 2021-03-30 09:36 UTC by maxlivinci

resolves #119

2021-03-30 09:36 UTC, maxlivinci commented on charts/murmurations/charts/index/templates/index/config.yaml
> +  RATE_LIMIT_PERIOD: 10-M
@geoffturk Feel free to change the value

2021-03-30 09:36 UTC, maxlivinci commented on charts/murmurations/charts/library/templates/library/config.yaml
> +  RATE_LIMIT_PERIOD: 10-M
same here

2021-03-30 10:27 UTC, geoffturk commented
@maxlivinci Is it possible to have more granular control over the rate limits? For example, it's OK to have a lot of reads (GETs) but we want to avoid a lot of writes (POSTs), so ideally we could control the limits for these two types of requests separately.

2021-03-30 10:41 UTC, geoffturk requested changes
See question above.

Also, can we return a JSON payload with an error description like we do for the 404?

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/32190662/112976469-33120a00-9155-11eb-9b5a-f841e5a7d096.png">

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/32190662/112976504-3d340880-9155-11eb-9ae9-76a800ae8f89.png">

2021-03-31 08:52 UTC, maxlivinci commented
![image](https://user-images.githubusercontent.com/11765228/113117901-7fd30f00-9241-11eb-8ea3-35f466eeefe4.png)

2021-03-31 09:36 UTC, geoffturk approved these changes
Perfect! LGTM 🚀

2021-03-31 09:41 UTC, merged