feat: add pagination to GET /nodes endpoint
MurmurationsNetwork/MurmurationsServices pull request #49
Opened 2020-11-20 10:02 UTC by maxlivinci

resolves #43

Note:

`from and size` won't able to search through more than 10,000 results.

![image](https://user-images.githubusercontent.com/11765228/99787245-75e62480-2b5a-11eb-8ac0-356a74779468.png)

[Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html)

2020-11-20 10:04 UTC, maxlivinci commented on services/index/internal/domain/query/es_query_dao.go
> +		Size:  math.Min(500, math.Max(1, q.PageSize)),
From:` 0 to any`
Size: `1 to 500`

2020-11-20 10:04 UTC, maxlivinci commented on services/index/internal/domain/query/es_query_dto.go
> +	PageSize float64 `form:"page_size,default=30"`
Page default 0
PageSize default 30

2020-11-22 09:03 UTC, geoffturk commented
There is an error in the counting of `total_pages`. See the failing test in the test suite.

![image](https://user-images.githubusercontent.com/32190662/99899488-f6676b00-2ca9-11eb-8cc2-91d1497c1071.png)


![image](https://user-images.githubusercontent.com/32190662/99899331-cb304c00-2ca8-11eb-8615-7f0203039bd2.png)

2020-11-22 09:04 UTC, geoffturk requested changes
See above.

2020-11-22 09:12 UTC, geoffturk commented
WTF?

https://play.golang.org/p/S42RViSVCBs

2020-11-22 09:54 UTC, geoffturk approved these changes
LGTM 🚀

2020-11-22 12:10 UTC, maxlivinci commented on common/pagination/pagination.go
> +	pages := math.Ceil(float64(numberOfResults) / float64(pageSize))
Good catch

2020-11-22 12:11 UTC, merged